ApeWorX/ape-alchemy

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- setup.py
> chore: prepare for beta

- ape_alchemy/providers.py
- setup.py
Handle changes from ApeWorX/ape#372
NOTE: The build will fail until we release. I am just opening this PR so we can do swift-releases afterward.
> chore: handle ape breaking changes regarding receipt status check

- README.md
- ape_alchemy/providers.py
- setup.py
Mentions environment variables options in the README
docccccs
read it
> docs:  add expected environment variables names to the README

- .github/workflows/test.yaml
- .pre-commit-config.yaml
- pyproject.toml
- setup.py
> chore: accept template updates

- ape_alchemy/providers.py
- tests/test_providers.py
> refactor: avoid attr dicts in trace requests for speed improvements

- ape_alchemy/providers.py
- tests/test_providers.py
> fix: grab result dict

- setup.py
upgrade pins to ape 0.4.0
setup.py
pytest
> chore: upgrade pin to ape 0.4.0

- .github/release-drafter.yml
- .github/workflows/commitlint.yaml
- .github/workflows/docs.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- setup.py
Aligning yaml files with ape core for consistency, after finding a yaml key name difference.
> chore: align yaml with ape core

- .github/workflows/test.yaml
- README.md
- ape_alchemy/__init__.py
- ape_alchemy/provider.py
- ape_alchemy/providers.py
- setup.py
- tests/conftest.py
- tests/test_integration.py
- tests/test_providers.py
> feat: add support for Optimism and Polygon

- .pre-commit-config.yaml
- ape_alchemy/provider.py
- setup.py
- tests/test_integration.py
> fix: add PoA middleware where needed

- ape_alchemy/provider.py
- tests/test_integration.py
fixes: #36 
Add middleware if 0th block needs it rather than latest.
See  test.
> fix: handle pre-merge PoA blocks for Ethereum goerli #37

- .pre-commit-config.yaml
- docs/conf.py
- setup.py
> chore: update linting

- .pre-commit-config.yaml
- ape_alchemy/provider.py
- setup.py
- tests/test_providers.py
The gas was incorrectly being set from the receipt and it included base costs and such.
It is not necessary!
> fix: issue with gas in top level call

- .github/workflows/commitlint.yaml
- .github/workflows/docs.yaml
- .github/workflows/prtitle.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- setup.py
> feat: python3.11 support [APE-1043]

- ape_alchemy/provider.py
> feat: private transaction [APE-1079]

- .github/workflows/codeql.yaml
- .github/workflows/commitlint.yaml
- .github/workflows/prtitle.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- setup.py
feat: add support for Python 3.12
chore: update lint dependencies
fixes: #
> feat: add support for python 3.12

- .github/workflows/test.yaml
- .pre-commit-config.yaml
- README.md
- ape_alchemy/exceptions.py
- ape_alchemy/provider.py
- setup.py
- tests/test_providers.py
fixes: #
Also requires https://github.com/ApeWorX/ape/pull/2090
> feat!: upgrade to 0.8

- .github/workflows/test.yaml
- .pre-commit-config.yaml
- README.md
- ape_alchemy/exceptions.py
- ape_alchemy/provider.py
- setup.py
- tests/test_providers.py
> feat!: Ape 0.8 updates

- .github/workflows/test.yaml
> test: re-enable macos-latest in CI

- ape_alchemy/__init__.py
- ape_alchemy/_utils.py
- ape_alchemy/provider.py
- setup.cfg
- tests/conftest.py
- tests/test_integration.py
Before:
```
In [1]: %time import ape_alchemy
CPU times: user 1.04 s, sys: 141 ms, total: 1.18 s
Wall time: 1.18 s
```
After:
```
In [1]: %time import ape_alchemy
CPU times: user 7.51 ms, sys: 2.64 ms, total: 10.2 ms
Wall time: 8.89 ms
```
all part of making ape load faster.
> perf: faster plugin load

- .pre-commit-config.yaml
- ape_alchemy/__init__.py
- setup.py
adds dependencies and __all__ to init
> perf: update perf improvements to match other plugins

- pyproject.toml
- setup.py
> chore: update setup tools version to newest

- setup.py
> chore: bump vers of `mdformat`

- ape_alchemy/_utils.py
> feat: add support for ethereum's holesky network

- .pre-commit-config.yaml
- pyproject.toml
- setup.py
- tests/test_integration.py
- tests/test_providers.py
> test: fix all-of-a-sudden failing tests

- ape_alchemy/_utils.py
- ape_alchemy/provider.py
- setup.py
> chore: ape compat upgrades

- README.md
- ape_alchemy/exceptions.py
- ape_alchemy/provider.py
- tests/test_providers.py
> feat: use demo key when keys not specified
